name: manage-azure-policy-7deb20b3
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Allowed_Application_Gateway_SKUs_1f8cdd0c-00f8-46e4-8eaa-11323ff17c95/**'
#      - .github/workflows/manage-azure-policy-7deb20b3.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_7deb20b3}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Allowed_Application_Gateway_SKUs_1f8cdd0c-00f8-46e4-8eaa-11323ff17c95/**
